changes

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,4 +1,4 @@
-name: Open My Network CI/CD
+name: Deploy WordPress to AWS EC2
 
 on:
   push:
@@ -7,54 +7,37 @@ on:
 
 jobs:
   build:
+    # Use the self-hosted runner
     runs-on: self-hosted
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Verify Docker is installed and running
+      - name: Log in to Docker Hub
+        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
+
+      - name: Build Docker image
         run: |
-          docker --version
-          sudo systemctl start docker
+          cd ~/wp_omn/_work/site-omn-wp/site-omn-wp
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/wordpress .
 
-      - name: Fix Docker socket permissions
-        run: sudo chmod 666 /var/run/docker.sock
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-        with:
-          driver: docker
-
-      - name: Login to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v2
-        with:
-          context: .
-          file: ./Dockerfile
-          push: true
-          tags: |
-            ${{ secrets.DOCKER_USERNAME }}/wordpress-app:latest
-            ${{ secrets.DOCKER_USERNAME }}/wordpress-app:${{ github.sha }}
-          platforms: linux/amd64
-
-      - name: Install Docker Compose
+      - name: Push Docker image to Docker Hub
         run: |
-          sudo curl -L "https://github.com/docker/compose/releases/download/v2.5.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-          sudo chmod +x /usr/local/bin/docker-compose
+          docker push ${{ secrets.DOCKER_USERNAME }}/wordpress:latest
 
-      - name: Deploy to Server
+  deploy:
+    runs-on: self-hosted
+    needs: build  # Ensure this job runs after the build job
+
+    steps:
+      - name: Pull Docker image to server
         run: |
-          # Pull the latest Docker images
-          docker-compose pull
+          docker pull ${{ secrets.DOCKER_USERNAME }}/wordpress:latest
 
-          # Stop and remove existing containers
-          docker-compose down || true
-
-          # Run the new containers using Docker Compose
-          docker-compose up -d
+      - name: Build and deploy Docker containers
+        run: |
+          set -e # exit on error
+          cd ~/wp_omn/_work/site-omn-wp/site-omn-wp
+          docker-compose down
+          docker-compose up -d --build
